ARCHS = armv7 arm64

include theos/makefiles/common.mk

APPLICATION_NAME = Test3
Test3_FILES = main.m Test3Application.mm RootViewController.mm
Test3_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
